global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]
  - job_name: 'inventory-service'
    metrics_path: '/actuator/inventory'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ] ## only for demo purposes don't use host.docker.internal in production
  - job_name: 'order-service'
    metrics_path: '/actuator/order'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ] ## only for demo purposes don't use host.docker.internal in production\
  - job_name: 'product-service'
    metrics_path: '/actuator/product'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ] ## only for demo purposes don't use host.docker.internal in production